# Railway.toml - Railway deployment configuration

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "bash entrypoint.sh"

# Environment variables to set in Railway dashboard:
# DATABASE_URL - Will be automatically provided by Railway PostgreSQL
# SECRET_KEY - Generate a secure secret key  
# DEBUG - Set to False for production
# ALLOWED_HOSTS - Set to your Railway domain
# CORS_ALLOWED_ORIGINS - Set to your frontend domain
